# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
# codex start
# codex (old code) minecraft_version=26.2
minecraft_version=1.21.4
# codex end
#yarn_mappings=1.21.4+build.8
loader_version=0.19.3
loom_version=1.17

# Mod Properties
# codex start
# codex (old code) mod_version=1.0
mod_version=1.0+1.21.4
# codex end
maven_group=com.example
archives_base_name=ironmansuit

# Dependencies
# codex start
# codex (old code) fabric_version=0.159.0+26.2
# codex (old code) sodium_version=mc26.2-0.9.1-fabric
fabric_version=0.119.4+1.21.4
sodium_version=mc1.21.4-0.6.13-fabric
# codex end